shell = "zsh"

[plugins]

[plugins.confd]
local = "~/.config/zsh/conf.d"

[plugins.completions]
local = "~/.config/zsh/completions"
apply = ['fpath']

[plugins.secrets]
local = "~/.config/zsh/secrets.d"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.omz-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.omz-kubectl]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/kubectl"

[plugins.lunar]
local = "~/go/src/github.com/lunarway/lw-zsh"

[plugins.lunar.hooks]
# initialize kubernetes and remove lunar keybinds 🙃
post = "which k8s_init > /dev/null && k8s_init benj@lunar.app && bindkey -d && bindkey -v"
