shell = "zsh"

[plugins]

[plugins.confd]
local = "~/.config/zsh/conf.d"

[plugins.completions]
local = "~/.config/zsh/completions"
apply = ['fpath']

[plugins.secrets]
local = "~/.config/zsh/secrets.d"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.omz-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.omz-kubectl]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/kubectl"

