import = [
    #"/Users/blacksails/.config/alacritty/themes/tokyonight_day.toml",
    #"/Users/blacksails/.config/alacritty/themes/tokyonight_night.toml",
    #"/Users/blacksails/.config/alacritty/themes/tokyonight_storm.toml",
    #"/Users/blacksails/.config/alacritty/themes/tokyonight_moon.toml",
    #"/Users/blacksails/.config/alacritty/themes/rose-pine.toml",
    "/Users/blacksails/.config/alacritty/themes/rose-pine-dawn.toml",
    #"/Users/blacksails/.config/alacritty/themes/rose-pine-moon.toml",
]

[env]
TERM = "alacritty-direct"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[window]
decorations = "None"
dynamic_padding = true

[window.padding]
x = 1
y = 1
